#@ load("@ytt:data", "data")
#@ load("@ytt:library", "library")
#@ load("@ytt:template", "template")

#@ def networking_values():
systemNamespace: #@ data.values.system_namespace
workloadsNamespace: #@ data.values.workloads_namespace
istiod:
  replicas: #@ data.values.istiod.replicas
#@ end

#@ networking = library.get("cf-k8s-networking")
--- #@ template.replace(networking.with_data_values(networking_values()).eval())

